name: Release Artifacts

on:
  push:
    branches:
      - main
  release:
    types: [created]

permissions:
  contents: 'write'
  id-token: 'write'


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        goos: [linux]
        goarch: [amd64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Build
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -v ./...

      - name: Test
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go test -v ./...

  release:
    if: github.event_name == 'release' && github.event.action == 'created'
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Build
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o out/auger main.go
      
      - name: package
        run: |
          tar -czvf auger-${{matrix.goos}}-${{matrix.goarch}}.tar.gz out/
      
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh release upload ${{github.ref_name}} auger-${{matrix.goos}}-${{matrix.goarch}}.tar.gz